# Byobu navigation
map --when-focus-on title:byobu$ super+1 send_text all \u00011
map --when-focus-on title:byobu$ super+2 send_text all \u00012
map --when-focus-on title:byobu$ super+3 send_text all \u00013
map --when-focus-on title:byobu$ super+4 send_text all \u00014
map --when-focus-on title:byobu$ super+5 send_text all \u00015
map --when-focus-on title:byobu$ super+6 send_text all \u00016
map --when-focus-on title:byobu$ super+7 send_text all \u00017
map --when-focus-on title:byobu$ super+8 send_text all \u00018
map --when-focus-on title:byobu$ super+9 send_text all \u00019
map --when-focus-on title:byobu$ super+0 send_text all \u00010

map --when-focus-on title:byobu$ super+[ send_text all \u0001\u0010
map --when-focus-on title:byobu$ super+] send_text all \u0001n

map --when-focus-on title:byobu$ super+shift+h send_text all \u0001h
map --when-focus-on title:byobu$ super+shift+j send_text all \u0001j
map --when-focus-on title:byobu$ super+shift+k send_text all \u0001k
map --when-focus-on title:byobu$ super+shift+l send_text all \u0001l

# Byobu tab/window management
map --when-focus-on title:byobu$ super+t send_text all \u0001c
map --when-focus-on title:byobu$ super+, send_text all \u0001,
map --when-focus-on title:byobu$ super+d send_text all \u0002%
map --when-focus-on title:byobu$ super+e send_text all \u0001|


# Byobu scrollback (copy-mode) with vim-like motions
map --when-focus-on title:byobu$ super+semicolon send_text all \u0001[
