// addSbtPlugin("org.ensime"          % "sbt-ensime"             % "2.2.1")
// addSbtPlugin("net.virtual-void"    % "sbt-dependency-graph"   % "0.9.0")
// addSbtPlugin("com.timushev.sbt"    % "sbt-updates"            % "0.3.3")
// addSbtPlugin("io.get-coursier"     % "sbt-coursier"           % "1.0.0-RC3")
// addSbtPlugin("com.scalapenos"      % "sbt-prompt"             % "1.0.2")
