addSbtPlugin("com.scalapenos"       % "sbt-prompt"              % "1.0.2")
addSbtPlugin("com.timushev.sbt"     % "sbt-updates"             % "0.3.4")
addSbtPlugin("io.get-coursier"      % "sbt-coursier"            % "1.1.0-M9")
addSbtPlugin("net.virtual-void"     % "sbt-dependency-graph"    % "0.9.2")
addSbtPlugin("org.ensime"           % "sbt-ensime"              % "2.5.1")
